sudo: false

services:
  - docker

script:
 - set -e
 - echo 'Build and check docker image'
 - docker build -t nf-paired-crispr .
 - docker images | grep -c nf-paired-crispr
 - echo 'Verify program(s) used by this repo'
 - docker run -t --rm nf-paired-crispr fastqc --help
 - docker run -t --rm nf-paired-crispr multiqc --help
 - docker run -t --rm nf-paired-crispr fqtools
